
#+TITLE: Taller - Conceptos Básicos de Hardware y Ensamblaje de Computadores
#+SUBTITLE: ICCD332 Arquitectura de Computadores
#+AUTHOR: [Nombres de los integrantes del grupo]
#+DATE: [Fecha de entrega]
#+OPTIONS: toc:nil num:t
#+LANGUAGE: es

#+latex_class: article
#+latex_class_options:
#+latex_header:
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_footnote_command: \footnote{%s%s}
#+latex_engraved_theme:
#+latex_compiler: latexmk

#+latex_header: \usepackage{fancyhdr}
#+latex_header: \usepackage[top=25mm, left=25mm, right=25mm]{geometry}
#+latex_header: \usepackage{longtable}
#+latex_header: \fancyhead[R]{}
#+latex_header: \setlength\headheight{43.0pt}
#+LATEX_HEADER: \usepackage{tabularx}
#+LATEX_HEADER: \usepackage{longtable}

#+cite_export: biblatex
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee]{biblatex}
#+BIBLIOGRAPHY: ../bibliography/bibliography.bib

#+begin_export latex
\fancyhead[C]{\includegraphics[scale=0.05]{../images/logoEPN.jpg}\\
ESCUELA POLITECNICA NACIONAL\\FACULTAD DE INGENIERIA DE SISTEMAS\\
ARQUITECTURA DE COMPUTADORES}
\thispagestyle{fancy}
#+end_export


* Instrucciones generales

  Este taller se realiza en *grupos*. Cada integrante debe completar
  individualmente el curso Cisco Networking Academy:
  *Conceptos Básicos de Hardware de Computadora* y obtener su
  certificado de completitud. 

  *Entregables del grupo:*
  - Resolución de éste archivo fuente ~.org~
  - El PDF exportado desde Emacs ~M-x org-latex-export-to-pdf~
  - Los certificados individuales de cada integrante (PDF o imagen)


  *Entregable Individual(Tarea):*
  -  Resolver el cuestionario individual en el aula virtual
** Recursos
Cree su usuario en la plataforma de /Cisco Networking Academy/. Use el
siguiente enlace:

[[https://www.netacad.com/es/courses/computer-hardware-basics?courseLang=en-US][Cisco Computer Hardware Basics]]

Puede configurar según el idioma de su preferencia. El texto está
disponible en Español. Los vídeos disponen de subtítulos en varios
idiomas.

* Parte A. Integrantes y certificados
Para insertar la captura del certificado utilice YASnippet: Escriba
~fig_~ seguido de ~C-TAB~. Esto produce ~#+caption~, ~#+attr_latex~ y
~#+label~ que permiten colocar un encabezado a la imagen, controlar el
escalado de la misma y una referencia. Finalmente inserte el enlace al
archivo usando ~C-c C-l~ o usando ~[[./carpeta-certificados/cert-int1.pdf]]~
1. *Integrante 1*
   - *Nombre completo:* Erick Sebastián Chicaiza Díaz
   - *Correo:* erick.chicaiza01@epn.edu.ec
   - *Certificado adjunto:*
     #+begin_example
      #+caption: Certificado Integrante 1
      #+attr_latex: scale=0.75
      #+label: fig:certificado-integrante-1
      [[./carpeta-certificados/certificado-integrante1.pdf]]
     #+end_example
2. *Integrante 2*
   - *Nombre completo:*
   - *Correo:*
   - *Certificado adjunto:*
     #+begin_src example
      Siga las instrucciones para insertar la imagen usando YASnippet
     #+end_src
3. *Integrante 3*
   - *Nombre completo:* Jonathan Pincay
   - *Usuario institucional:*
   - *Correo:* jonathan.pincay01@epn.edu.ec
   - *Certificado adjunto:* (sí / no)
     #+begin_src example
      Siga las instrucciones para insertar la imagen usando YASnippet
     #+end_src
     
* Parte B. Cuestionario argumentado grupal

Para cada pregunta:

- Indique la alternativa escogida (letra).
- Escriba una justificación técnica breve (3 a 6 líneas). Fundamente
  su respuesta. Su insumo principal es el curso de Conceptos Básicos
  de Hardware. Si usa otro material referenciar.
- Discuta con el grupo de trabajo las opciones y la respuesta ¿Existió
  consenso? ¿Cuáles fueron las principales discrepancias?

*Criterio:* correcto/incorrecto + calidad del argumento técnico.

** Pregunta 1 
Al instalar una CPU en un socket LGA, ¿por qué es crítico alinear el
pin 1 de la CPU con el pin 1 del socket?

a. Para que el sistema arranque con mayor rapidez

b. Para evitar daños en la CPU y el socket al insertar incorrectamente

c. Porque el pin 1 es el único que conduce electricidad 

d. Para que el disipador quede centrado automáticamente

- /Alternativa escogida:/ b
- /Justificación técnica:/ El socket esta diseñado para que la CPU sea colocada en una sola orientación, si
  es que se llega a instalar de forma incorrecta, el procesador o los pines pueden resultar dañados de forma permanente.
  El alinearlos correcamente evita que al cerrar el socket, este dueble o rompa los pines.
- /Debate del grupo:/ Existio un consenso entre todo el grupo para  obtener esta respuesta. Todos recordamos que el poner
  mal el CPU en el socket, este puede sufrir graves daños.
  
** Pregunta 2 
Al montar la placa madre en el gabinete, ¿cuál es la función de los separadores (standoffs)?

a. Sostener el peso de las tarjetas de expansión

b. Evitar cortocircuitos entre la placa madre y el metal del gabinete

c. Mejorar la ventilación de la placa madre

d. Facilitar la alineación del panel de E/S trasero

- /Alternativa escogida:/ [a completar]
- /Justificación técnica:/ [a completar]
- /Debate del grupo:/ [a completar]

** Pregunta 3 
Según el manual de ensamblaje de Cisco, ¿cuándo NO es necesario aplicar pasta térmica al instalar el disipador sobre la CPU?

a. Cuando la CPU es de alto rendimiento

b. Cuando el disipador ya incluye pasta térmica preaplicada

c. Cuando la CPU tiene más de un año de uso

d. Cuando el gabinete tiene buena ventilación

- /Alternativa escogida:/ [a completar]
- /Justificación técnica:/ [a completar]
- /Debate del grupo:/ [a completar]

** Pregunta 4 --Jonathan
¿Por qué se recomienda usar pulsera antiestática y alfombrilla antiestática al manipular componentes internos?

a. Para proteger al técnico de descargas de 220 V

b. Para evitar que la electricidad estática dañe los componentes

c. Para cumplir una norma estética del laboratorio

d. Para que los tornillos no se magneticen

- /Alternativa escogida:/ b
- /Justificación técnica:/ Se recomienda usar pulsera antiestática y alfombrilla antiestática debido a que el cuerpo humano puede acumular ciertas cantidades de electricidad estática, dicha carga puede llegar a dañar los componentes internos tales como el procesador o la memoria RAM, entre otros, al afectar los circuitos integrados en ellos. La pulsera antiestática se conecta a una toma de tierra para redirigir la carga hacia tierra y mantener equilibradas las cargas eléctricas y la alfombrilla evita que los componentes reciban cargas estáticas de la mesa de trabajo.
- /Debate del grupo:/ Desde el inicio existió un consenso en la respuesta elegida ya que todos habíamos realizado el curso de cisco y allí se encontraba la respuesta clara sobre esta pregunta por lo que no hubo discrepancias al momento de elegir.
** Pregunta 5 
Si al iniciar la computadora por primera vez un LED del panel frontal no funciona, ¿qué indica el manual de Cisco?

a. Reemplazar el conector por uno de repuesto

b. Revisar el BIOS para habilitar el LED

c. Quitar el conector, invertirlo y volver a conectarlo

d. Desconectar y reconectar la fuente de poder

- /Alternativa escogida:/ c
- /Justificación técnica:/ Al ser un diodo LED, estos presentan una polaridad negativa y positiva en sus cables,
  de modo que si se colocan con una polaridad incorrecta, estos no se van a encender. La solución a esto es girar el LED
  180 grados para que quede polarizado correcamente.
- /Debate del grupo:/ Hubo un pequeño debate entre la opción a y c, ya que por nuestro criterio, estas son dos opciones posibles
  ante este problema que el LED no se encienda.

** Pregunta 6 --Nicole
¿Por qué una GPU puede requerir un conector de alimentación PCIe adicional de la fuente de poder?

a. Porque la ranura PCIe no transmite señal de video

b. Porque las GPUs de alto rendimiento consumen más potencia de la que la ranura puede suministrar

c. Porque el conector PCIe solo funciona con tarjetas de red

d. Por el estándar de codificación de color de los cables SATA

- /Alternativa escogida:/ [a completar]
- /Justificación técnica:/ [a completar]
- /Debate del grupo:/ [a completar]

* Parte C. Mantenimiento de computadores

** 3.1 Insumos para mantenimiento preventivo --Sebastian
   Liste al menos seis insumos y describa para qué sirve cada
   uno. Revise el siguiente [[https://youtu.be/3ri1BMV7XTM?si=bjYoDUUKuMWwj4Qg][vídeo]].

   | Insumo | Uso principal |
   |--------+---------------|
   |        |               |
   |        |               |
   |        |               |
   |        |               |
   |        |               |
   |        |               |

** 3.2 Procedimiento de limpieza — Desktop --Jonathan 
   1. Primero se empieza con el desarmado para ello se apaga el equipo, se coloca el interruptor de la fuente de poder en 0 y se desconecta el cable de alimentación y se presiona el botón de encendido durante unos segundos para descargar la energía residual de los componentes.
   2. Después se procede a retirar las tapas laterales del gabinete, se desconectan los cables de alimentación de la placa madre y la tarjeta gráfica para más seguridad y se extraen los componentes principales retirando los tornillos que los fijan al chasis.
   3. Se utiliza una sopladora con mucho cuidado para remover el polvo del gabinete, se bloquean las aspas de los ventiladores y se limpian adecuadamente con un cepillo de cerdas suave y alcohol isopropílico.
   4. Se limpia por completo la pasta térmica reseca del procesador y del disipador haciendo uso de un papel sin pelusas y del alcohol isopropílico. Cuando este limpio el chip se aplica una nueva gota de pasta térmica en el centro.
   5. Finalmente se vuelve a colocar el disipador sobre el procesador y se ajustan los tornillos en forma de cruz alternando cada uno para equilibrar la presión, se reinstala la tarjeta gráfica en su ranura, se aseguran los tornillos al chasis y se reconectan los cables de energía para cerrar las tapas del gabinete.
** 3.3 Procedimiento de limpieza — Laptop --Erick
   1. Limpiar el gabinete exterior con un paño suave que no deje pelusa apenas humedecido con agua o con una solución de limpieza suave
   2. Limpiar los orificios de ventilación y puertos de E/S con aire comprimido o una aspiradora no electrostática.
   3. Limpiar la pantalla con un paño suave que no suelte pelusa ligeramente humedecido con un limpiador de pantallas de computadora.
   4. Limpiar el teclado con un paño suave que no suelte pelusa ligeramente humedecido con agua o una solución de limpieza suave.
   5. Limpiar la superficie del panel táctil suavemente con un paño suave que no suelte pelusa humedecido con un limpiador aprobado. No utilizar paños mojados.

* Parte D. Aprendizaje obtenido -- Cada uno 

** Integrante 1 [Erick Sebastián Chicaiza Díaz]
   - *¿Qué conocimiento nuevo obtuvo del curso?*
     Todos los temas tratados en el curso fueron nuevos para mi, aunque conocia algunos términos, no sabia donde usaban o donde aplicarlos. He logrado aprender sobre
     el proceso de monstaje y desmontaje de una computadora de escritorio o laptop, además de la utilidad que tiene cada componente para el correcto funcionamiento de
     estos equipos.
     El modulo sobre dispositivos moviles como celulares tambien resulto interesante, ya que explicó como se dio el desarollo y evolución de dispositivos tan grandes
     hasta ser tan pequeños que caben en nuestro bolsillo.
     
   - *¿Qué concepto corrigió o clarificó?*
     Con este curso pude corregir un error que tenia al limpiar mis equipos con alcohol. Ahora se que esto puede resultar en daños en mis dispositivos, por lo que
     obtendre recursos de limpieza adecuados.

** Integrante 2 [Nombre]
   - *¿Qué conocimiento nuevo obtuvo del curso?* [Respuesta]
   - *¿Qué concepto corrigió o clarificó?* [Respuesta]

** Integrante 3 Jonathan Pincay
   - *¿Qué conocimiento nuevo obtuvo del curso?*
El conocimiento que obtuve al realizar este curso fue que aprendí a identificar cada componente interno que existe dentro de un dispositivo, además de ello también aprendí el verdadero funcionamiento que realiza cada componente y como estos trabajan en equipo.
   - *¿Qué concepto corrigió o clarificó?* 
El concepto que corregí fue acerca las fuentes de poder ya que antes pensaba que mientras más cantidad de Watts tuviera sería mejor pero al realizar el curso entendí que si dicha fuente es una fuente genérica puede poner en riesgo los componentes de mi dispositivo y que por esa razón una fuente con certificación siempre sera mejor incluso si no tiene los mismos Watts.
     
* Rúbrica de evaluación

  | Criterio                               | Puntaje máximo |
  |----------------------------------------+----------------|
  | Certificados individuales completos    |             20 |
  | Cuestionario: respuesta correcta (x8)  |             30 |
  | Cuestionario: argumento técnico (x8)   |             30 |
  | Mantenimiento (tabla + procedimientos) |             20 |
  | TOTAL                                  |            100 |

* ¿Cómo referenciar en Emacs?
Para insertar una referencia a un recurso bibliográfico
1. Puede actualizar el archivo ~../bibliography/bibliography.bib~
2. Escribir en formato **BibTeX** el recurso bibliográfico
3. Verifique la siguiente configuración al encabezado:
   #+begin_src org
   #+cite_export: biblatex
   #+LATEX_HEADER: \usepackage[backend=biber, style=ieee]{biblatex}
   #+BIBLIOGRAPHY: ../bibliography/bibliography.bib
   #+end_src
4. Usar ~M-x org-cite-insert~ para insertar una cita. Aparecerá una
   lista. Use los cursores para seleccionar la cita. Ejecute ~C-RET~: /De acuerdo con
   [cite:@ledin2022modern], la arquitectura ...../
5. Revise que al final del documento exista ~#+print_bibliography:~
6. **Sugerencia:** Para evitar repetir varias veces el proceso de
   exportación, es recomendable cambiar el compilador de \LaTeX a
   ~latexmk~. Para esto:
   - ~sudo apt install latexmk~
   - Revise en el encabezado del ~.org~ que el compilador escogido sea
     ~#+LATEX_COMPILER: latexmk~. También puede modificar el archivo
     ~init.el~ para indicar qué compilador se usa para exportar de
     ~.org~ a /LaTeX/:
     #+begin_src elisp
;; 4.7b Proceso de compilación con latexmk para Org-export
(with-eval-after-load 'ox-latex
  (setq org-latex-pdf-process
        '("latexmk -f -pdf -%latex -interaction=nonstopmode -output-directory=%o %f")))

;; 4.7c Org-cite: biblatex como procesador para exportación LaTeX
(with-eval-after-load 'oc
  (setq org-cite-export-processors
        '((latex biblatex)
          (t basic))))

     #+end_src
* Verificación de Entregables [0%]:
Ejecute ~C-c C-c~ sobre los ítems de tarea según se hayan cumplido o
no. Si un ítem no pudo realizarse apunte en la siguiente sección las
razones al respecto.
- [ ] Los enlaces a los certificados en el documento ~.org~ funcionan.
- [ ] Resolución completa del Cuestionario2.
- [ ] Revisión del vídeo sobre mantenimiento a computador ASUS. 
- [ ] Tutorial de Comandos Emacs realizado.
- [ ] Lista de insumos para mantenimiento completa.
- [ ] Procedimiento de mantenimiento para desktop completo.
- [ ] Procedimiento de mantenimiento para laptop completo.
- [ ] Revisión de ortografía con ~ispell-buffer~ en el buffer
- [ ] Generación de Archivo PDF ~M-x org-latex-export-to-pdf~
- [ ] Subir al aula virutal archivo ~.org~ y ~.pdf~

#+print_bibliography:
